# Generated by Django 2.2.9 on 2020-01-15 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploadapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='content',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
