# Generated by Django 2.2.5 on 2019-12-28 19:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mycontact',
            name='photo',
            field=models.ImageField(
                blank=True,
                upload_to='myproject/DjangoApp/static/img/'),
        ),
        migrations.AddField(
            model_name='mycontact',
            name='user',
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='mycontacts',
                to=settings.AUTH_USER_MODEL),
        ),
    ]
